using System.Collections.ObjectModel;
using TradingStrategySimulator.Domain.Entities;
using TradingStrategySimulator.Domain.Enums;
using TradingStrategySimulator.Domain.Models;
using TradingStrategySimulator.Domain.ValueObjects;

namespace TradingStrategySimulator.Domain.Aggregates;

/// <summary>
/// Aggregate root representing one complete simulation request and outcome.
/// 
/// A simulation run groups together:
/// - the asset being simulated
/// - the selected strategy
/// - the input price history
/// - the trades generated by that strategy
/// - the final calculated result
/// 
/// This keeps the simulator aligned with DDD thinking:
/// one aggregate root representing one complete business operation.
/// </summary>
public sealed class SimulationRun
{
    private readonly List<PricePoint> _priceSeries;
    private readonly List<Trade> _trades;

    public Guid Id { get; }

    public Asset Asset { get; }

    public StrategyType StrategyType { get; }

    public decimal InitialCash { get; }

    public int QuantityPerTrade { get; }

    public SimulationConstraints Constraints { get; }

    public IReadOnlyCollection<PricePoint> PriceSeries => new ReadOnlyCollection<PricePoint>(_priceSeries);

    public IReadOnlyCollection<Trade> Trades => new ReadOnlyCollection<Trade>(_trades);

    public SimulationResult? Result { get; private set; }

    public SimulationRun(
        Guid id,
        Asset asset,
        StrategyType strategyType,
        decimal initialCash,
        int quantityPerTrade,
        IEnumerable<PricePoint> priceSeries,
        SimulationConstraints constraints)
    {
        if (id == Guid.Empty)
        {
            throw new ArgumentException("Simulation run id is required.", nameof(id));
        }

        Asset = asset ?? throw new ArgumentNullException(nameof(asset));

        if (initialCash < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(initialCash), "Initial cash cannot be negative.");
        }

        if (quantityPerTrade <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(quantityPerTrade), "Quantity per trade must be greater than zero.");
        }

        if (priceSeries is null)
        {
            throw new ArgumentNullException(nameof(priceSeries));
        }

        Constraints = constraints ?? throw new ArgumentNullException(nameof(constraints));

        _priceSeries = priceSeries.ToList();

        if (_priceSeries.Count == 0)
        {
            throw new ArgumentException("Price series is required.", nameof(priceSeries));
        }

        _trades = [];
        Id = id;
        StrategyType = strategyType;
        InitialCash = initialCash;
        QuantityPerTrade = quantityPerTrade;
    }

    public void SetTrades(IEnumerable<Trade> trades)
    {
        if (trades is null)
        {
            throw new ArgumentNullException(nameof(trades));
        }

        _trades.Clear();
        _trades.AddRange(trades);
    }

    public void Complete(SimulationResult result)
    {
        Result = result ?? throw new ArgumentNullException(nameof(result));
    }
}